### ISSUE TITLE
Fragile \@ifstar's

### ISSUE THREAD

**Issue by jspitz** [josephwright/csquotes#16]
It appears like `biblatex`, in some cases, stumbles over definitions that use `\@ifstar`. This also applies to `\enquote*` in bibliography fields (see https://github.com/plk/biblatex-apa/issues/35).

Although I don't blame `csquotes` for this, I'd like to mention that I have fixed this problem in a package of my own by using `xparse` for command creation and star parsing, i.e. via `\NewDocumentCommand` and the `s` arg spec, and I wonder whether this won't be worth doing in `csquotes` as well. It might make `csquotes` more robust.

**Comment by josephwright** [comment]
Interesting question: I  agree that moving to `xparse` might be the right choice now. I'll think about this: it's a non-trivial change but then again `xparse` is now very widely used/available (probably more-or-less akin to having LaTeX at all).

**Comment by jspitz** [comment]
I also think `xparse` could be made a prerequisite for current versions of `csquotes`. It is most likely available in all distributions that would offer a 2017 version of `csquotes`.

**Comment by eg9** [comment]
I agree with @jspitz that `xparse` should by now be considered as available.

**Comment by car222222** [comment]
Is 'considered as available' an official status?  Just to note that if such a status is announced anywhere, the non-final status of sparse needs to be naḍe clear to potential users.

**Comment by josephwright** [comment]
@car222222  I think we've been clear on which parts of `xparse` (as a LaTeX2e package) are stable. I meant more that making `csquotes` depend on `xparse` does work on the basis that for most users this will be transparent, so they therefore already need to have `xparse` available.

**Comment by wspr** [comment]
I agree with @eg9's agreeing.

**Comment by eg9** [comment]
To be more precise, the part of `xparse` dealing at least with `m o O s` argument types should be evidently marked as *stable*; I'd also add the `+` modifier, because this is probably needed in `csquotes`.

**Comment by josephwright** [comment]
I've been pondering this: I'm not sure the issue is `protected` status for the out macros nor now arguments are grabbed, but rather that in the linked case two tokens (`\enquote*`) are replaced by one (`\ienquote`). Doesn't mean `xparse` can't be used, but it might not solve the issue raised (which will need me to work on the relevant internals).

**Comment by josephwright** [comment]
@eg9  Indeed: I'll update the docs to be explicit. Perhaps we should cover that in LaTeX(3) News?

**Comment by eg9** [comment]
@josephwright Maybe raise on the team list?

**Comment by jspitz** [comment]
@josephwright, note that in the case where I use `xparse`, I don't use the `\ienquote` workaround mentioned in plk/biblatex-apa#35.
Both solutions fix the error for me.

**Comment by josephwright** [comment]
@jspitz  Could do with an example (perhaps by email?)

**Comment by jspitz** [comment]
@josephwright a minimal example is given in the OP of plk/biblatex-apa#35.

**Comment by jspitz** [comment]
I have re-evaluated this issue, and it turned out the problem is in `biblatex`'s definition of `\MakeSentenceCase`. 

I'll move this issue over to `biblatex`.

**Comment by jspitz** [comment]
For the records: https://github.com/plk/biblatex/issues/941
