### ISSUE TITLE
Adding Hungarian support

### ISSUE THREAD

**Issue by ferdinandyb** [josephwright/csquotes#19]
I made a fork [https://github.com/priestoferis/csquotes](https://github.com/priestoferis/csquotes) where I will try to add Hungarian support. I opened this issue to track progress and be able to ask questions, if I need help.

**Comment by moewew** [comment]
This just came up again in https://tex.stackexchange.com/q/428749/35864 According to Wikipedia

```latex
\documentclass[magyar]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}

\DeclareQuoteStyle{magyar}
  {\quotedblbase}
  {\textquotedblright}
  [.05em]
  {\guillemotright}
  {\guillemotleft}

\begin{document}
\enquote{Lorem \enquote{ipsum} dolor}


\enquote{Lorem \enquote{ipsum}}

\enquote{\enquote{Lorem} ipsum}
\end{document}
```
might be a good starting point. This would still need verification and the kern value (the optional argument) would need looking at - one could go with 0, but to me a little space looked a bit nicer, not sure what the customs are here in Hungarian.

**Comment by ferdinandyb** [comment]
This is going to be in Hungarian, but I'm quoting the relevant parts of spelling rules of the [Hungary Academy of Sciences](https://helyesiras.mta.hu/helyesiras/default/akh12) (12th edition, 2015):

> Az idézőjel lehet: „ ” (macskaköröm) vagy » « (lúdlábidézőjel). Az első idézőjel az alapforma, a második általában idézeten belüli idézőjel, például: Jókai írja: **„Ahogy a halászok mondják: »beszél a víz«”.** Az idézőjel páros írásjel. Alapformájában a kezdő idézőjel mindig alsó, a berekesztő idézőjel felső helyzetű. A kezdő idézőjelet szóközzel kell elválasztani az előtte álló szó utolsó betűjétől vagy számjegyétől, az utána álló szó (vagy számjegy, írásjel) azonban mindig szóköz nélkül kapcsolódik az idézőjelhez. A berekesztő idézőjelhez az előtte álló szó utolsó betűje (vagy az előtte álló számjegy), valamint más írásjel mindig tapad, míg utána szóközt kell tenni. Például: **Eltöprengve áll a gépe mellett, s nézi, hogyan omlik ki a dagasztógép „hurkatöltőjéből” a végtelen kenyérfolyam**.

So this explicitly states that wikipedia is right about the first and second level quotes.

> Az összetételek keletkezésének (azaz az egybeírásuknak) többféle forrása lehet: 1. a tagok együttes jelentésének megváltozása (nyitvatartás ’üzemidő’);

This does not explicitly state the meaning thing, but there are several examples like this, so it seems this is also true.

As for the spacing: I will look in some printed books, but a little space seems to be there.

**Comment by moewew** [comment]
In case anyone missed it (I certainly had), Hungarian support was added in https://github.com/josephwright/csquotes/commit/23b8f2a27946eac9dafd8eba3283dfb4ec88602c.

**Comment by ferdinandyb** [comment]
Great! I missed it also, but at least it concluded this issue, I'll close it then.
