### ISSUE TITLE
Adding Estonian support

### ISSUE THREAD

**Issue by kristiank** [josephwright/csquotes#22]
I would like to add support for Estonian quotes, but I am unsure how to do it by looking at the code [here](https://tex.stackexchange.com/questions/166337/quotation-mark-quotation-sign-xelatex-polyglossia-csquotes). Maybe it would be possible to just point me in a direction of a conversion table between Unicode characters and LaTeX names and I might be able to solve it my self?

I know these marks „“ (e.g 99 below and 66 above) are the, let's say most correct quotation marks to use in Estonian (http://keeleabi.eki.ee/?leht=8&id=270). Probably it would be nice to also allow the French/Russian guillemets, because they are used in some larger newspapers (but never in academia).

**Comment by josephwright** [comment]
The syntax itself is pretty straight-forward: see `csquotes.def`. Probably you want to start from one of the existing set ups and adapt it: often it's just a case of copying and changing the name.

**Comment by kristiank** [comment]
Made a pull request.

**Comment by kristiank** [comment]
I'll reopen this, since my pull request has received zero comments. Is there any chance this will be pulled soon?

**Comment by kristiank** [comment]
thank you
