### ISSUE TITLE
Undefined control sequence \langname

### ISSUE THREAD

**Issue by schlcht** [josephwright/csquotes#30]
Since the last update, the following will yield the above error:

```
\documentclass{article}
\usepackage[german,british]{babel}
\usepackage[babel]{csquotes}
\begin{document}
\foreignquote{german}{Das Zitat}
\end{document}
```

because in this definition `\langname` should be `\languagename` I guess -:

```
\def\csq@savelang{%
  \ifdef\csq@mainlang
    {}
    {\ifdef\babelname
       {\edef\csq@mainlang{\babelname}}
       {\edef\csq@mainlang{\langname}}}}
```

**Comment by moewew** [comment]
Sorry for that typo :-( Fix is at https://github.com/josephwright/csquotes/pull/32.

And sorry for only seeing this now...
