### ISSUE TITLE
\hyphenquote gives undefined error

### ISSUE THREAD

**Issue by daleif** [josephwright/csquotes#33]
MWE:

\documentclass{article}
\usepackage[english]{babel}
\usepackage[english=american]{csquotes}
\begin{document}
\hyphenquote{english}{test}
\end{document}

Error:

! Undefined control sequence.
<argument> \edef \csq@mainlang {\langname 
                                          }
l.5 \hyphenquote{english}{test}

File versions:

*File List*
 article.cls    2019/10/25 v1.4k Standard LaTeX document class
  size10.clo    2019/10/25 v1.4k Standard LaTeX file (size option)
   babel.sty    2019/11/14 3.36 The Babel package
 english.ldf    2017/06/06 v3.3r English support from the babel system
csquotes.sty    2019-11-14 v5.2g context-sensitive quotations (JAW)
etoolbox.sty    2019/09/21 v2.5h e-TeX tools for LaTeX (JAW)
  keyval.sty    2014/10/28 v1.15 key=value parser (DPC)
csquotes.def    2019-11-14 v5.2g csquotes generic definitions (JAW)
csquotes.cfg    

System: TUG TeXLive 2019, fully up to date (as per tlmgr)

**Comment by DoraPaula** [comment]
the same over here, additionally:

Undefined control sequence. \textquote, \foreigntextquote

**Comment by DoraPaula** [comment]
fix available here: https://github.com/josephwright/csquotes/pull/32

**Comment by josephwright** [comment]
Fixed by https://github.com/josephwright/csquotes/pull/32
