### ISSUE TITLE
Feature request: Provide separate open and close quote commands

### ISSUE THREAD

**Issue by schtandard** [josephwright/csquotes#41]
I recently found myself wanting to typeset some verbatim text in quotation marks. Since all of the inline quotation commands provided by `csquotes` consume the text to be quoted as an argument, this is not possible using it. An interface to produce only the opening or the closing quotation mark would be useful for cases like this.

Maybe an environment would be best, so outer and inner quotes can still be selected automatically, though typing an environment inline would be rather akward.

**Comment by moewew** [comment]
Probably I misunderstand what you are looking for, but it seems to me that `\openautoquote`/`\closeautoquote` might help you.

```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}

\begin{document}
Lorem \enquote{ipsum} dolor
\enquote{sit \enquote{amet} consectur}

Lorem \openautoquote ipsum\closeautoquote\ dolor
\openautoquote sit \openautoquote amet\closeautoquote\ consectur\closeautoquote
\end{document}
```

---

If you don't want (or can't) use the automatic level selection, you can go full manual mode with
```latex
Lorem \textooquote ipsum\textcoquote\ dolor
\textooquote sit \textoiquote amet\textciquote\ consectur\textcoquote
```
Though in that case it may or may not be necessary to execute the hooks `\initoquote` and `\initiquote` in a group when you call the relevant marks.

**Comment by schtandard** [comment]
No, that's exactly what I was asking for, thanks for the hint. Just did not search that far back in the documentation.. It _did_ seem a weird feature to be missing, though.
