### ISSUE TITLE
Add this repository to CTAN and/or the package documentation

### ISSUE THREAD

**Issue by schtandard** [josephwright/csquotes#42]
This repository is neither linked on [CTAN][ctanpage], nor is it mentioned in the package documentation. Since it is probably better for people to file bug reports and feature requests here than via email, maybe change that?

[ctanpage]: https://ctan.org/pkg/csquotes

**Comment by rugk** [comment]
Yes, I had to mail the maintainer to find it, I also had the same issue: https://github.com/josephwright/csquotes/issues/51

**Comment by josephwright** [comment]
> Yes, I had to mail the maintainer to find it, I also had the same issue: #51

That is the traditional way ;)

**Comment by rugk** [comment]
Well… there are reasons why one uses issue trackers/the advantages of them, and I think they are pretty clear/well-known, so I like the “modern” way much more… :stuck_out_tongue_winking_eye:

**Comment by josephwright** [comment]
As I inherited `csquotes`, I realise there is no link in the docs: that's probably something I should fix
