### ISSUE TITLE
Need the comma after the quoted title in Greek

### ISSUE THREAD

**Issue by jokogr** [josephwright/csquotes#5]
As I have posted in josephwright/biblatex-ieee#20, I am using biblatex-ieee and polyglossia for writing my thesis in Greek and have references appearing like this

```
[63] P. R. Wilson, M. S. Johnstone, M. Neely και D. Boles, «Dynamic Storage Allocation: A Survey and Critical Review,» στο IWMM, 1995, σσ. 1–116.
```

I have the impression that in Greek it is more preferred to have the comma after the quotes, e.g., `«Dynamic Storage Allocation: A Survey and Critical Review»,`. Would this be possible via _csquotes_?

**Comment by josephwright** [comment]
Can you put together a short example input file?

**Comment by jokogr** [comment]
Sure thing:

```
\documentclass{article}

\usepackage{fontspec}
\setmainfont{Liberation Serif}
\setsansfont{Liberation Sans}
\newfontfamily\greekfont{Liberation Serif}

\usepackage{polyglossia}
\setdefaultlanguage[variant=mono]{greek}
\setotherlanguage{english}
\usepackage{csquotes}

\usepackage{filecontents}

\begin{filecontents}{jobname.bib}
  @inproceedings{wilson_dynamic_1995,
  title = {Dynamic {Storage} {Allocation}: {A} {Survey} and {Critical} {Review}},
  booktitle = {{IWMM}},
  author = {Wilson, Paul R. and Johnstone, Mark S. and Neely, Michael and Boles, David},
  year = {1995},
  pages = {1--116},
}
\end{filecontents}

\usepackage[backend=biber,style=ieee]{biblatex}
\bibliography{jobname}

\begin{document}
\nocite{*}
\printbibliography
\end{document}
```

In order to run it you need to have the Liberation fonts installed, XeLaTeX and Biber, e.g., if you name the tex file `test.tex`:

```
xelatex test
biber test
xelatex test
```

**Comment by jokogr** [comment]
@josephwright Have you tested the short example I wrote for you? Have you found any workaround?

**Comment by jspitz** [comment]
This is unrelated to csquotes. It is due to the standard setting of biblatex-ieee, which uses `\uspunctuation` (a switch provided by biblatex, see its manual).
Insert `\stdpunctuation` after loading biblatex. This will change  to the punctuation scheme you prefer,

**Comment by josephwright** [comment]
As noted, this is really 'by design' for `biblatex-ieee` and relates to the fact it's hard to separate out 'style of the bibliography' and 'typographic tradition for the place the style is from'!

**Comment by jokogr** [comment]
Many thanks for your support, using `\stdpunctuation` solved my issue.
