### ISSUE TITLE
polyglossia, french and spacing

### ISSUE THREAD

**Issue by maieul** [josephwright/csquotes#7]
This is a complex issue, because related to the fix of the issue on a other package.

In french, there is space after opening guillemet (<code>«</code>) and before closing one (<code>»</code>). Normaly, csquotes let polyglossia manage it.

However polyglossia 1.24 break the automatic insertion (cf https://github.com/reutenauer/polyglossia/issues/141). The problem was for some user who inserted space if filesource, like this following:

```
\enquote{ 1 }
"  5 "
« 5 »
```

I think, I have found a way to solve the <code>« 5 »</code> example: cf https://github.com/reutenauer/polyglossia/issues/141#issuecomment-216058509.

But this does not work when using `\enquotes` command.

Cf this MWE

```
\documentclass{article}
\usepackage{polyglossia}
\setmainlanguage{french}
\usepackage[french=guillemets]{csquotes}
\MakeOuterQuote{"}
\makeatletter
\XeTeXinterchartoks \french@punctguillstart 255 = {\nobreakspace\xpg@nospace\ignorespaces}% "« " -> "«~"
\makeatother
\begin{document}


« 1 » % Not csquotes
\enquote{ 1 } % Csquotes
"  5 " % Csquotes
\end{document}
```

My suggestion : should it be csquotes automatically gobble the spurious space after / before opening/closing quotation in the sourcefile, and let polyglossia (debuged) manage it ?

**Comment by josephwright** [comment]
Seems to be OK with an up-to-date TeX system: can you check?

**Comment by maieul** [comment]
OK, I have update my TeXLive 2016, and make new test.

First, test with correction of a bug of polyglossia, bug mentionned on https://github.com/reutenauer/polyglossia/issues/141.
The correction, in the following MWE is on the `\appto` structure.

With this correction, which is just a coming back to the older version of polyglossia, there is still a problem with <code>" 3 "</code>. Without this correction, there is no problem with <code>" 3 "</code>, but many problem with other tests. And, last but not least, this correction is just a coming back to the older behavior of polyglossia.

Here the MWE

```
\listfiles
\documentclass{book}
\usepackage{polyglossia}
\setmainlanguage{french}
\usepackage{csquotes}
\makeatletter
%\appto\french@punctuation{%
%     \XeTeXinterchartoks \french@punctguillstart 4095 = {\nobreakspace\xpg@nospace}% "«  " -> "«~"
%     \XeTeXinterchartoks 4095 \french@punctguillend = {\xpg@unskip\nobreakspace}% "  »" -> "~»"
%     \XeTeXinterchartoks 4095 \french@punctthin = {\xpg@unskip\nobreak\thinspace}%
%     \XeTeXinterchartoks 4095 \french@punctthick = {\xpg@unskip\nobreakspace}%  
%}
\MakeOuterQuote{"}
\makeatother
\begin{document}

\enquote{1}%With correction on Polyglossio : OK ; without correction of polyglossia : NOT OK

"2"%With correction on Polyglossio : OK ; without correction of polyglossia : NOT OK

" 3 "%With correction on Polyglossio : NOT OK ; without correction of polyglossia :  OK

«4»%With correction on Polyglossio : OK ; without correction of polyglossia : OK

« 5 »%With correction on Polyglossio : OK ; without correction of polyglossia :  OK


\end{document}
```

And my listfiles:

```
This is XeTeX, Version 3.14159265-2.6-0.99996 (TeX Live 2016) (preloaded format=xelatex)
 restricted \write18 enabled.
entering extended mode
(./bis.tex
LaTeX2e <2016/03/31> patch level 3
(…)
 *File List*
    book.cls    2014/09/29 v1.4h Standard LaTeX document class
    bk10.clo    2014/09/29 v1.4h Standard LaTeX file (size option)
polyglossia.sty    2015/03/25 v1.42.4 Alternative to Babel for XeLaTeX and LuaL
aTeX
etoolbox.sty    2015/08/02 v2.2a e-TeX tools for LaTeX (JAW)
makecmds.sty    2009/09/03 v1.0a extra command making commands
 xkeyval.sty    2014/12/03 v2.7a package option processing (HA)
 xkeyval.tex    2014/12/03 v2.7a key=value parser (HA)
fontspec.sty    2016/02/01 v2.5a Font selection for XeLaTeX and LuaLaTeX
   expl3.sty    2016/05/18 v6512 L3 programming layer (loader) 
expl3-code.tex    2016/05/18 v6512 L3 programming layer 
l3xdvipdfmx.def    
  xparse.sty    2016/05/18 v6512 L3 Experimental document command parser
fontspec-xetex.sty    2016/02/01 v2.5a Font selection for XeLaTeX and LuaLaTeX
 fontenc.sty
  eu1enc.def    2010/05/27 v0.1h Experimental Unicode font encodings
  eu1lmr.fd    2009/10/30 v1.6 Font defs for Latin Modern
xunicode.sty    2011/09/09 v0.981 provides access to latin accents and many oth
er characters in Unicode lower plane
 eu1lmss.fd    2009/10/30 v1.6 Font defs for Latin Modern
graphicx.sty    2014/10/28 v1.0g Enhanced LaTeX Graphics (DPC,SPQR)
graphics.sty    2016/07/10 v1.0t Standard LaTeX Graphics (DPC,SPQR)
    trig.sty    2016/01/03 v1.10 sin cos tan (DPC)
graphics.cfg    2016/06/04 v1.11 sample graphics configuration
   xetex.def    2016/07/11 v4.10 LaTeX color/graphics driver for XeTeX (L3/RRM/
JK)
fontspec.cfg
ifluatex.sty    2016/05/16 v1.4 Provides the ifluatex switch (HO)
 ifxetex.sty    2010/09/12 v0.6 Provides ifxetex conditional
gloss-french.ldf    polyglossia: module for french
csquotes.sty    2016/07/14 v5.1h context-sensitive quotations (JAW)
csquotes.def    2016/07/14 v5.1h csquotes generic definitions (JAW)
csquotes.cfg    
   t3cmr.fd    2001/12/31 TIPA font definitions
 ***********

 )
```

**Comment by maieul** [comment]
hi,

I is strange you closed this file?

You didn't reproduce the bug ?

**Comment by josephwright** [comment]
@maieul Based on your post of the 7/10/16, the issues is at the `polyglossia` end as I understand it, hence closing. Do I miss something?

**Comment by maieul** [comment]
my suggestion was that csquotes gobble automatically spurious spaces, which will make it not dependant of language manager…

**Comment by josephwright** [comment]
@maieul The question then is whether one regards the space as part of the argument! In the main, LaTeX arguments preserve leading/trailing spaces so one would expect the 'correct' input to be `"5"`. The 'extra' spaces in French typography are part of the 'furniture' not part of the 'text' so are here not in the argument.

**Comment by maieul** [comment]
ok. thanks.
I agree with you that the correct input should be "s". I will try to covince polyglossia maintener to come back to the previous and standard behavior
