### ISSUE TITLE
TeXLive 2016 breaks french space in "guillemet"

### ISSUE THREAD

**Issue by maieul** [josephwright/csquotes#8]
Consider this MWE, run with XeLaTeX:

```
\listfiles
\documentclass{article}
\usepackage{polyglossia}
\usepackage{csquotes}
\setmainlanguage{french}
\makeatletter
\apptocmd{\french@punctuation}{%
     \XeTeXinterchartoks \french@punctguillstart 255 = {\nobreakspace\xpg@nospace}% "«  " -> "«~"
     \XeTeXinterchartoks 255 \french@punctguillend = {\xpg@unskip\nobreakspace}% "  »" -> "~»"  
}{}{}
\makeatother
\begin{document}

\enquote{x}

«x»
\end{document}
```

The makeatletter/makeatoher code is to conturn bug in polyglossia (cf https://github.com/josephwright/csquotes/issues/7 and https://github.com/reutenauer/polyglossia/issues/141), and was working well in TeXLive2015.

So we got space inside the quotation mark, which is the attempted behavior.

![texlive2015](https://cloud.githubusercontent.com/assets/636640/15822355/96a5ad6c-2bf5-11e6-96a5-7cdead7086ab.png)

With TeXLive2016, we get not the space in the `\enquote` command.
![texlive2016](https://cloud.githubusercontent.com/assets/636640/15822377/b9ca35b0-2bf5-11e6-8928-678cd3ce908d.png).

Enclosed, the result of the listfiles for the two texlive.
[2015.txt](https://github.com/josephwright/csquotes/files/300411/2015.txt)
[2016.txt](https://github.com/josephwright/csquotes/files/300410/2016.txt)

I have tried to get back to the files of TeXLive2015 > same problem. So the issue must be in the change of XeTeX engine… indeed, running LuaLaTeX is working.
cc @aurelberra

**Comment by josephwright** [comment]
The engine now has more classes available, meaning the special 'none of the above' class is now 4095 rather than 255.
